GophKeeper
EvgeniyBudaev/gophkeeper pull request #1
Opened 2024-02-19 13:27 UTC by EvgeniyBudaev

2024-02-20 06:55 UTC, gonozov0 requested changes
Запишись плиз на 1:1, мне нужно понять верхнеуровневую архитектуру, какой интерфейс взаимодействия с пользователем, как будет работать синхронизация. Все это довольно долго понимать из кода и стоило обговорить еще до его написания 🙂

2024-02-26 08:24 UTC, gonozov0 requested changes
Прекрасное начало 👍
Предложил улучшения

2024-02-26 08:24 UTC, gonozov0 commented on cmd/client/bin/gclient
В директории cmd не должно находиться ничего, кроме модулей с main.go файлами для клиента и сервера

2024-02-26 08:24 UTC, gonozov0 commented on cmd/client/bin/gclient
Все бинарные файлы также не должны быть запушены, принято, чтобы в Makefile была удобная команда для их сборки. Сама директория bin должна быть в корне проекта

2024-02-26 08:24 UTC, gonozov0 commented on cmd/client/internal/logic/login.go
> +	httpclient := client.GetHTTPClient()
Обычно как раз таки наоборот, логгер получают через синглтон, а все клиенты уже приходят аргументами инициализированные. Я бы поменял, но не настаиваю

2024-02-26 08:24 UTC, gonozov0 commented on internal/utils/user.go
> +func CreateUsersDir(username string) error {
Стоит создавать в домашнее директории пользователя + "." + название приложения

2024-02-26 08:24 UTC, gonozov0 commented on cmd/client/internal/logic/records.go
> +	}
Если пользователь залогинен, то у него уже должна быть эта директория, кажется бессмысленно

2024-02-26 08:24 UTC, gonozov0 commented on cmd/client/internal/logic/records.go
> +	ext := utils.GetExtension(data.Type)
Всю логику получения пути к файлу и запись стоит инкапсулировать. Например, создать LoginPassRepo (LoginPassAdapter) и реализовать там просто публичные методы Add, Update, Delete, а всю логику с файлами скрыть. И так для каждого типа

2024-02-26 08:24 UTC, gonozov0 commented on internal/app/app.go
> +	maxCookieAge = 3600 * 24 * 30
Куки не корректное название в контексте cli + также нигде не увидел проверки на то, что токен протух по этому значению

2024-02-26 08:24 UTC, gonozov0 commented on migrations/20240219063504_DataRecordsCreationMigration.up.sql
> +    blocked BOOLEAN NOT NULL
Что значит blocked? is_deleted? Если это флаг удаления пользователем записи, то не совсем понимаю, зачем этот флаг сохранять в самой бд, он нужен, чтобы понять, что запись нужно просто удалить из бд (если конечно это самая новая операция)

2024-02-27 08:10 UTC, gonozov0 requested changes
Супер быстро все правишь, респект)
Отписал еще комментарии

2024-02-27 08:10 UTC, gonozov0 commented on client/cmd/main.go
Давай поподробней опишу структуру для кода, на самом верхнем уровне у нас 2 пакета:
- cmd
- internal

Внутри cmd:
- client (в нем main.go для клиента)
- server (в нем main.go для сервера)

Внутри internal:
- client (внутри уже вся бизнес логика для клиента)
- server (внутри уже вся бизнес логика для сервера)

У тебя может быть свое видение структуры и это отлично, но главное правило для хорошего разработчика, что все нужно делать *консистентно*
То есть если на вехнем уровне модуль client, а в нем уже cmd и internal, то точно также должно быть и для server

2024-02-27 08:10 UTC, gonozov0 commented on client/internal/cmd/login.go
> +package cmd
Я бы этот пакет лучше назвал cli, не конфликтует с названием модуля на другом уровне и лучше отражает суть

2024-02-27 08:10 UTC, gonozov0 commented on cmd/gophkeeper/main.go
> +		conn.Close()
лучше тоже через defer

2024-02-27 08:10 UTC, gonozov0 commented on client/internal/logic/records.go
> +func PutRecord(ctx context.Context, args []string) (*models.DataRecord, error) {
Стоит добавить еще шифрование при добавление записи и расшифровку при получении. Кто-то из студентов предложил, чтобы пользователь каждый раз вводил мастер пароль. Можно сделать так или просто заставлять пользователя вводить его один раз при логине и сохранять на устройстве (но не отправлять на сервер)

2024-02-27 08:10 UTC, gonozov0 commented on client/internal/logic/records.go
> +	endpoint, _ := url.JoinPath(httpclient.APIURL, "api/user/records", name)
Мы при вводе команды пользователем на создание/изменение/получение данных не должны ходить на сервер, это все должно работать без интернета, работа тут только с локальным хранилищем.
Взаимодействие с сервером должно быть только при команде синхронизации

2024-02-27 13:50 UTC, EvgeniyBudaev commented on client/internal/logic/records.go
> +	endpoint, _ := url.JoinPath(httpclient.APIURL, "api/user/records", name)
Спорный момент.  В современных реалиях на каждое действие клиент обращается к серверу за актуальными данными, т.к.  клиент должен получить одинаковые данные на разных устройствах на момент запроса.  Должно работать без интернета, этот подход применяется в проектах для гос учреждений, где необходим дополнительный уровень секретности. Оба варианта имеют право на существование. В техническом задании о том, что это должно работать без интернета ничего не сказано

2024-02-27 13:56 UTC, EvgeniyBudaev commented on client/internal/logic/records.go
> +func PutRecord(ctx context.Context, args []string) (*models.DataRecord, error) {
Я бы предложил этому студенту внедрить в качестве сервиса авторизации  - keycloak или другой аналогичный сервис и не заниматься изобретением велосипедов) Я отталкиваюсь от технического задания, в котором эти процедуры не описаны

2024-02-27 15:06 UTC, EvgeniyBudaev commented on client/internal/logic/records.go
> +func PutRecord(ctx context.Context, args []string) (*models.DataRecord, error) {
Добавил шифрование при добавлении записи и расшифровку при получении

2024-02-27 15:06 UTC, EvgeniyBudaev commented on cmd/gophkeeper/main.go
> +		conn.Close()
поправил

2024-02-27 15:06 UTC, EvgeniyBudaev commented on client/internal/cmd/login.go
> +package cmd
поправил

2024-02-27 15:06 UTC, EvgeniyBudaev commented on client/cmd/main.go
поправил

2024-02-28 09:12 UTC, gonozov0 approved these changes
Работа сдана 👍

2024-02-29 04:14 UTC, merged